---
- name: Converge
  hosts: all
  tasks:
    - name: "Include daixijun.keepalived"
      include_role:
        name: "daixijun.keepalived"
      vars:
        keepalived_version: 2.0.20
        keepalived_vrrp_scripts:
          - name: chk_check_file
            script: "/usr/bin/test -f /tmp/keepalived_test_check.txt"
            weight: -10
        keepalived_vrrp_instances:
          - name: VI_CHECK_FILE
            state: BACKUP
            interface: eth0
            virtual_router_id: 50
            advert_int: 1
            track_script:
              - chk_check_file
            authentication:
              type: PASS
              pass: 1111
            virtual_ipaddress:
              - 172.17.0.100/24
